name: Test

on: [push, pull_request]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
